### ISSUE TITLE
Ring of Flames

### ISSUE THREAD

**Issue by Maikeljr** [cyberjunk/meridian59-dotnet#101]
Self cast it...it not only lags you horribly, but spams you with a crap ton of symbols. Works fine in original client, self cast is suicide in Ogre Client atm.

**Comment by cyberjunk** [comment]
I can't really reproduce this so far.

Trying to self-cast Ring of Flames on my local server, gives me:
>> Jan 30 2016 02:24:07|[rngflame.bof (85)] Ring of Flames cast will nil target list

and nothing happens. I fixed a small issue with the cast-request sending in general, but that's rather unrelated. The "crap ton" of symbols in chat that you describe usually happen due to an oudated RSB file. Please make sure you run an up-to-date version from the OpenMeridian patcher....

**Comment by skittles1** [comment]
While fixing the RoF target issue I was also unable to reproduce the lag, gonna guess that was a consequence of outdated RSB file and printing all the symbols.
