### ISSUE TITLE
New servers won't show up on the login screen for patched clients.

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#112]
Since patching doesn't overwrite configuration.xml any longer, patched clients won't display any new servers listed. There should probably be a way to output missing server profiles from code to configuration.xml, was wondering how you wanted to handle it (I could attempt to add it if you don't have time).

**Comment by cyberjunk** [comment]
Yes that's a good point. Since current clients got their configuration.xml already, the new entries are not added. There is some code to handle fully missing xml tags, but nothing for handling default entries in collections so far....

I think the best solution would be this:
Adjust the config loader/parser functions for the connectionprofiles (or find another good place) to add some code that runs through the loaded entries and verifies all default entries exist (match by name/ip/port/etc..)

**Comment by skittles1** [comment]
I'll try to implement this... have another question though: for the new server (105) I converted all the mp3s to .ogg format, and on the test server (106) I've also converted the wavs. The audio sounds the same but combined this saves ~100mb total, however it's implemented in the kod files by changing .mp3 and .wav to .ogg.

Unless everyone else wants to switch their code to also have .ogg, Ogre would be playing sounds on some servers and not on others. I'm thinking the solution would be to have Ogre only include the .ogg audio to save on size, and if it tries to play a .wav or .mp3, always change the extension to .ogg before opening the file. If you think this is the right solution I can try implement that also.

**Comment by cyberjunk** [comment]
Hey thanks for doing all this.

About the sound files:
Currently sounds are strictly WAV and music is strictly MP3. To change this I suggest

a) Edit the method "Init()" in "Meridian59.Files.ResourceManager"
When it registers all the filenames in the sound and music folder, simply filter for all three kinds (wav, mp3, ogg) in both three cases instead of only one. This makes sure all variants of the possibly existing audio files get registered.

b) Edit the Methods "GetWavFile()" and "GetMusicFile()" also in "Meridian59.Files.ResourceManager". In case retrieving the value from the server fails in the TryGetValue() call there (e.g. server sent sound.ogg and client has only sound.mp3), try retrieving the additional variants you registered in (a), e.g. instead of sound.ogg, try looking up sound.mp3, if it fails, try sound.wav)

I guess something like this ?

**Comment by skittles1** [comment]
I was thinking more along the lines of add the .ogg files to Ogre resources submodule and remove the .mp3 and .wav files and then make sure every request for a sound file has the .ogg extension (change from .wav/.mp3 if not). Would work for vanilla also which may always have .wav/.mp3 resources, while lowering the size of the Ogre client by 100mb.

**Comment by skittles1** [comment]
Also we could have the "sound" ogg files in sound\ and "music" ones in music\ if the distinction is still useful.

**Comment by cyberjunk** [comment]
>> I was thinking more along the lines of add the .ogg files to Ogre resources submodule and remove the .mp3 and .wav files and then make sure every request for a sound file has the .ogg extension (change from .wav/.mp3 if not). Would work for vanilla also which may always have .wav/.mp3 resources, while lowering the size of the Ogre client by 100mb.

Hmm yes that sounds good, too. So OgreClient would always require the .ogg files in the directories, read only this .OGG filetypes in the mentioned Init() function and then do a string replacement of the .mp3 and .wav etc extensions to .ogg somewhere on the filenames received from the server? This 'somewhere' could either be the "ResolveStrings()" function which models "PlaySound" and "PlayMusic" implement (replace extensions to .ogg here), or you can put it into the ResourceManager's GetWavFile()/GetMusicFile() functions. Not yet sure which I would prefer, may be first...

>> Also we could have the "sound" ogg files in sound\ and "music" ones in music\ if the distinction is still useful.

Given the fact they both use the same fileformat, the distinction is not really useful anymore.
It was based on the fact that these types might need different player implementations, which is neither true for ogre nor classic client I guess.

**Comment by skittles1** [comment]
Thinking maybe we should keep sounds and music separate then, also since players will often turn off/turn down music while playing it would still need to be separate in UI.
