### ISSUE TITLE
Game-Mail to long

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#135]
Reported:

If a gamemail is to long, it shows that that the lettering is too long, but then close the window instead going back and give the user a opportunity to shorten the gamemail.

**Comment by cyberjunk** [comment]
There is no check on the maximum length so far.
This shouldn't be too hard to implemented...

1) Find the server constant which currently defines the maximum length for newsglobe postings/mails etc.

2) Define this maximum size somewhere in the C# core lib (project Meridian59 - if in doubt, Common.Constants.Constants.cs or may be somewhere in Protocol namespace or wherever...)

3) Use the constant as argument in 'setMaxTextLength()' on the text UI elements, like in:
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/UINewsGroupCompose.cpp
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/UIMailCompose.cpp

**Comment by cyberjunk** [comment]
I have started fixing this.
Next version, the input controls will prevent entering oversized strings according to server-limits.

* Limit guild name and rank names in the new guild creation window
* Limit avatar name in new avatar creation window
* Limit news-globe title and text lengths
* Limit chat-input length
* ..

**Comment by skittles1** [comment]
BTW I believe the current issues on classic/ogre with mail length are due to the subject being included in the same string as the mail text, but the server-side checks only accounting for the length of the mail text. The server might have to parse the mail and check each part, or just allow for text length + subject length.

**Comment by cyberjunk** [comment]
I haven't checked the server side in detail.
However it seems to work fine for the newsglobe postings...
Should be quire comparable (title+text), may be we can just adopt the code from this?

**Comment by cyberjunk** [comment]
This is fixed in https://github.com/cyberjunk/meridian59-dotnet/commit/33e27ab6ebbb6e235e31c118cb22b4f6c2b8cafd

OgreClient now reserves up to 60 characters for the title and uses the rest of the combined limit for the body. So it's not possible anymore to enter more than allowed and endup with a lost unsent mail.
