### ISSUE TITLE
Copy in Chat/Mail window

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#136]
Right now you cant copy lettering in the chat/mail window. Is there a possibility to include that?

Edit: The key ^ doesnt work, is there a reason why?

**Comment by cyberjunk** [comment]
>> Right now you cant copy lettering in the chat/mail window. Is there a possibility to include that?

You can copy & paste in the mail and newsglobe windows.
However you can't do it in the chat and I can't just activate it....

It's a limitation of the UI framework and caused by the coloring/styling of the text there. As soon as this is enabled, the ability to select chunks of the text is gone (and copy+paste with it).

**Comment by MorbusM59** [comment]
@cyberjunk 
Do you see absolutely no way around that? As it is, this seems to be the single biggest issue why people choose classic over ogre: The inability to copy chat. This is made even worse by the fact that some disciple quests require you to bring a message to another NPC, pushing people's noses right into the issue.

Is there no way to color editbox text on the fly or to make static text slectable at all? 

As for the chat.log file, most people have issues even locating the install folder. The log itself is really useful, but we really have to assume zero tech background users that need to be told to check if they plugged the power chord into the outlet. And not being able to copy chat is a big issue for most users I've talked to.

(Being honest, it is confusing as hell. I believe my latest version was installed to "C:\Users\Username\AppData\Local\Open Meridian\Meridian DotNet\x64" while my previous version was installed to "C:\Program Files\Open Meridian\Meridian DotNet\x64". I also have some classic client version in "C:\Program Files (x86)\Open Meridian\Meridian 103". I know this is totally off topic, but is there any reason we don't allow users to pick the directory themselves?)

**Comment by cyberjunk** [comment]
>> Do you see absolutely no way around that?

Sadly not :-( It's a CEGUI limitation. So it's more like a CEGUI todo than an Ogre...
Selection is only possible on the editboxes, but they don't support the coloring/styling :-/

You can try out yourself:
Change the _TaharezLook/StaticText_ to _TaharezLook/MultiLineEditbox_ in the 'Chat' part of the _Meridian59.layout_

You will be able to to make selections on the text,
But you will see all the internal CEGUI markup instead of colors etc.
In fact the M59 style markup is translated to this internal CEGUI markup.

>> As for the chat.log file, most people have issues even locating the install folder.

Agree. I think we could at least add a startmenu shortcut so people can access it more easily?

Others are also just workarounds: e.g. could allow users to switch chat between unselectable colored and uncolored selectable or something like that.

**Comment by MorbusM59** [comment]
@cyberjunk Are you able to keep track of new posts to old issues when I don't reference your name? Not sure if you do, so I'm abusing the feature for now... 

Anyway, a shortcut to chat.log might help actually.

Also I've already tried what you suggested and seen the issue you mentioned. :/

I found this here, which seems to be another guy with the same issue and someone suggesting stuff: http://cegui.org.uk/forum/viewtopic.php?t=5297

I guess, adding support for FormattedRenderedString to editbox widgets isn't something that can be done in a reasonable amount of time (even though I'm not quite sure why it's that different from statictext...) 

How viable is the other suggested approach of creating a double layer UI with identical statictext and mleb, that shows the statictext but uses the mleb for copy purposes? I don't really have a clear idea of what text selection would look like in that case. The entire thing seems a bit glitchy... I guess you could have the mleb text completely hidden the entire time, but show the selection highlight?

I'd really hate to give up on this.

**Comment by cyberjunk** [comment]
>> Anyway, a shortcut to chat.log might help actually.

This probably needs to go into the installer. Need to talk to @skittles1 about it.
Two problems however:
1) Two Chat.log in folders x86 and x64, we might end up with 2 shortcuts :-/
2) The files don't exist at first. May be the installer would need to create them with 0 size or so...

>> http://cegui.org.uk/forum/viewtopic.php?t=5297

That is a good source. But I don't seem to see a solution in it.
They just suggest to use _StaticText_ for their inlined formatting or give some general hints how the styling is implemented :(

>> I guess, adding support for FormattedRenderedString to editbox widgets isn't something that can be done in a reasonable amount of time (even though I'm not quite sure why it's that different from statictext...)

Can't tell you that either. But I'm afraid it's not just a few lines or otherwise someone would have done it already.

>> How viable is the other suggested approach of creating a double layer UI with identical statictext and mleb, that shows the statictext but uses the mleb for copy purposes?

I had something like this in mind (a) or (b):

a) Adding a tab-panel into the chat-window with two tabs. One showing chat like now (styled, no copy+paste), the other one would be plain text only in a MultiLineEditbox (grey text only, but copy+paste). It's already easy to access the text without formatting styles (see Chat.log, it does not contain ~B~r etc.)

b) Adding a Button/Checkbox/... to the Chat-Window to let user switch between the two variants mentioned in (a)

But these are clearly only workarounds..

**Comment by skittles1** [comment]
I'm reluctant to add a shortcut to chat.log for the reasons mentioned, plus this is something that should be handled in the client if possible (by fixing CEGUI or providing an unformatted chat tab alongside the formatted one).

Morbus, the install directory was changed from Program Files to AppData around April as many of the client issues players were having were due to not having rights to edit/load files correctly from Program Files (the easiest fix was to just move the install directory). The location is not changeable by the user as it makes the installers easier to write/use, and also because (for developers only) when you build the client locally it gets files from the classic client's resource directory which the build script assumes is in AppData (but does still check Program Files for backwards compatibility). Ogre installs to AppData since it uses mostly the same code in the installer plus makes sense to keep the clients together.

**Comment by MorbusM59** [comment]
I see, that does make sense, Del.

I prefer option b) for now, simply because it is the cleaner solution. We could add that as additional system buttons, next to the close button. We might also want to implement tabs for splitting up the chat log into chat and combat spam. We could have another systembutton to toggle between the two views. I believe that would make most users happy.

**Comment by cyberjunk** [comment]
>> Morbus, the install directory was changed from Program Files to AppData around April as many of the client issues players were having were 

I think the current situation is also not perfect.
What actually happens if you switch the user on the system?
The other user likely has no access to the files in appdata of the other user?
But still sees the program installed in system panel...
Each windows user would have to install the clients separatedly etc.
Also the shortcuts are in the roaming subfolder startmenu of appdata, while the client itself is in the local appdata. That would also break on roaming profiles etc...

**Comment by cyberjunk** [comment]
>> I prefer option b) for now, simply because it is the cleaner solution. We could add that as additional system buttons, next to the close button. We might also want to implement tabs for splitting up the chat log into chat and combat spam. 

I think (a) and (b) are pretty close, it's more a visual question. Add the toggle somewhere into the chatwindow, or place it somewhere else? Another mainbutton wasn't really my intention...

About the chat splitting: That is a bit off-topic. I think there is an improvement issue for it, but currently the server-sent that does not provide the capability to separate them like that.

**Comment by MorbusM59** [comment]
Yeah, tabs are more of a long term issue I guess.
I'd like the toggle next to the close button in the titlebar (internally called SysArea). But I can really play around with the visual implementation. However, I have absolutely no idea how I would get started with the actual coding.

What it could look like: 
![button](https://cloud.githubusercontent.com/assets/4948485/18846223/3619b96a-8425-11e6-939d-637afb0c8936.png)

**Comment by cyberjunk** [comment]
Version 1.0.4.9 allows switching the chat to a new 'plain' mode by right mouse click. Plain mode does not have any colors or other styles, but instead allows selecting text for copy+paste.

Issue can likely be closed then.
