### ISSUE TITLE
Buying without Target isnt possible

### ISSUE THREAD

**Issue by novemr** [cyberjunk/meridian59-dotnet#14]
Should be working like with the vanilla client, i.e. using the nearest npc/mob to attack or buy/trade. Maybe adding a selection box for trading, if you dont have a target and multiple "possible targets" in range.

**Comment by AlgorithmsOfMathdestruction** [comment]
I agree, this feature is missing.

**Comment by cyberjunk** [comment]
Next version 1.0.3.6 will allow you to attack the enemy in front of you without targetting it first.
Not sure if I've also added it for buying yet.

Basically I didn't want to implement this feature ('do something without target') at first, because to me it seems rather uncommon for modern MMORPGS and was one of the 'shooter' elements of M59.

I however DO agree at least for farming it's a nice improvement :)

**Comment by skittles1** [comment]
Isn't this one fixed as of 1.0.4.5?
