### ISSUE TITLE
Paragraphs in mail and newsgroup messages are not recognized by the classic client.

### ISSUE THREAD

**Issue by MorbusM59** [cyberjunk/meridian59-dotnet#166]
As an example
this text will
look like this
text in classic.

As an examplethis text willlook like thistext in classic.

**Comment by skittles1** [comment]
You mean text created in Ogre client mail/postings won't show up correctly in classic?

**Comment by MorbusM59** [comment]
Exactly.

**Comment by cyberjunk** [comment]
Interesting. Never noticed this.
What you're saying is:

Creating a mail/newsgroup posting with Classic works fine in Classic+Ogre with regard to new-line characters? But creating a mail/newsgroup posting with Ogre will not work correctly in Classic?

Is that right?

I would expect there's something wrong with the new-line characters. May be one is using "\n" and the other "\n\r" or one at least can't handle both variants?

**Comment by MorbusM59** [comment]
Yup. Paragraphs created by Classic are visible in Classic and Ogre.
Paragraphs created by Ogre are only visible in Ogre, not in Classic.

**Comment by skittles1** [comment]
Classic client wants \r\n but Ogre posting only contains \n. @cyberjunk should I modify classic to insert the \r when it finds a lone \n or did you want Ogre to add the \r?

**Comment by MorbusM59** [comment]
Have we actually fixed this?

**Comment by cyberjunk** [comment]
>> Have we actually fixed this?

I have not yet made any changes so far...
According to what we discussed, it seems CEGUI uses only '\n' by default and classic needs '\r\n'.

I searched the CEGUI sources for the '\n' constant and came up with several places it is hardcoded into. Most promising might be [this](https://github.com/cyberjunk/meridian59-engine/blob/bdbd5f329472c483bc654020f8be33cccbe024ea/src/cegui-0.8.5/src/widgets/MultiLineEditbox.cpp#L87) definition, but I have not yet tried to change it.

I already have to maintain a couple of CEGUI changes/patches, which I have to reintegrate/apply when I migrate to new CEGUI version. And I'm not really looking for more of such custom changes to their codebase. :-(

So I would definitely prefer both clients being able to support both, '\n' as well as '\r\n'.
I think this kind of approach is proably better anyways, because it is more robust and the network communication basically allows any arbitrary new-line character.

Another solution would be forcing this or that one by the server (e.g. scan and replace), but that's probably just unwanted payload..

**Comment by skittles1** [comment]
Yes, this is really a classic bug/missing feature.

**Comment by cyberjunk** [comment]
There is one solution on Ogre side I think.
I can implement this low-level in the byte serializers of the corelib classes.

Replace any '\n' by '\r\n' before sending the text to the server

**Comment by skittles1** [comment]
This is now fixed in the classic client (in the develop branch, not live until early next week).

**Comment by MorbusM59** [comment]
<3 No more switching to classic just to post in the globe. :D

**Comment by skittles1** [comment]
Fix (to classic client) is live now, can close this one.
