### ISSUE TITLE
103 - NPC and PC names not showing

### ISSUE THREAD

**Issue by Maikeljr** [cyberjunk/meridian59-dotnet#213]
I got 103 ogre client working with the new items, but can't solve the lack of character/npc names.

**Comment by cyberjunk** [comment]
What do you mean by:
>> the lack of character/npc names

These string resources are stored in the _rsc0000.rsb_ file.
You have to add the updated one that you build with your server and classic client to the OgreClient resources.

You will also find an _OPENMERIDIAN_ preprocessor flag at least in _Config.cs_. Make sure to use it when you build all the stuff, it's supposed to switch some parts to OpenMeridian compatibility rather than VANILLA or 105/112 (default).

**Comment by Maikeljr** [comment]
Once you log on, no NPC or PC have a name posted above the character models. It works properly on 105 and 112, but not on 103.

**Comment by cyberjunk** [comment]
I assume the names are shown fine in the debug window?
There have been several changes to the objectflags I think.

I guess this might be your problem:
https://github.com/cyberjunk/meridian59-dotnet/commit/f95076b099b5762491be20baae113b57c981078f

Try replacing the
>> #ifdef VANILLA

By:
>> #ifdef VANILLA || OPENMERIDIAN

And of course build using OPENMERIDIAN.
Or implement the "IsDisplayName" thing on 103. I think it does not exist yet.
Other places might need adjustments too.
