### ISSUE TITLE
Some Character-Names dont get displayed on lists like "Who plays/Entities"

### ISSUE THREAD

**Issue by tyras2** [cyberjunk/meridian59-dotnet#222]
Characters with a name like `[UserXY]` don't get displayed on the "Who plays/Entities" and any other Lists. 

Not sure if there are more ways to name a charater that he dont get displayed.

**Comment by cyberjunk** [comment]
Good catch.
I expect this is related to the CEGUI "formatting tags" that are used to format and colorize text.

See here:
http://cegui.org.uk/wiki/Formatting_Tags_in_CEGUI

I guess that this is activated for the given elements and hence the [xyz] is parsed rather than displayed. The linked contains the used escape character, probably a "\" needs to be inserted in front of any existing "["

**Comment by cyberjunk** [comment]
Escaping the opening "[" is only handled for chat so far:
https://github.com/cyberjunk/meridian59-dotnet/blob/master/Meridian59.Ogre.Client/UIChat.cpp#L209

**Comment by cyberjunk** [comment]
Should be fixed in this commit, which disables CEGUI formatting tags for all elements of type _Label_ by default:

https://github.com/cyberjunk/meridian59-dotnet/commit/aec8d12a685d0494fa8943400661b9b34c096193

**Comment by tyras2** [comment]
Great job, thanks so much

**Comment by cyberjunk** [comment]
Fix in latest release
