### ISSUE TITLE
Movement checks use different heights

### ISSUE THREAD

**Issue by skittles1** [cyberjunk/meridian59-dotnet#85]
Possibly due to a height check in Ogre client, players are unable to fit through the gap leading to the last area in Thrashers before the chest.

Here's an image of the blocked part: http://i.imgur.com/3WOfHZF.png

**Comment by cyberjunk** [comment]
This is an interesting point.
I just reviewed the code and currently the object-height, which is used in move validation in OgreClient looks like this:

>> float playerheight = 0.88f * 16.0f * Avatar->SceneNode->_getWorldAABB().getSize().y;

Means it is based on the actual height of your current avatar's shape - it's basically the height of the object boundingbox that you see in debug-builds. Assuming you morph into a rat, your collisions in Ogre would be different.

I'm not exactly sure how the height is handled in the old client, on the server we just work with a fixed height....

**Comment by cyberjunk** [comment]
I renamed this, because I think the original spot in that map has been fixed, but in general the problem still exists. I think clients use slightly different ways to calculate height into collision check.

On the server for example, all objects have a constant height.
On Ogre, object height is dependent on bgf object size (=actual size).
Not sure about the old client.

**Comment by cyberjunk** [comment]
Closing this, probably fixed since a while ago...

When I rewrote the Ogre movment collisions based on server-code, I also changed the assumed height from something dynamically referred from the 3D object (as explained above), to the fixed object height constant also used on the server-side...
