### ISSUE TITLE
want to try to contribute, some handholding needed ;)

### ISSUE THREAD

**Issue by m59solo** [cyberjunk/meridian59-dotnet#86]
Hello,

i want to check out the OgreClient and try to add some features and there are some major roadblocks for me.

(former Delphi-Developer, low c# and c++ experience, but can learn ;)

**Is there a wiki and a crash course for github and the build process in VC2013?**

I installed github desktop, cloned the repository to local, make a new branch called "playingwithogre".
Is this the prefered way to get changes to the project?

First strange thing (for me) is the project scope: it is the whole meridian59-dotnet. Thought i can just download the ogreclient-part, but that was a misunderstanding, maybe.

So i installed VC 2015, it wont open the project, bc source is 2013. Convert is not an option, i think, so:
I installed VC 2013.

If i open the Project-File in the Ogre-folder, it nevertheless opens the whole project, with all tools and stuff. Is there a simpler way?

I tried to build just the Ogre-Part but it seem there are dependencies, AdminUI was the first one - so i try to build this too, but it fails with ImageComposerGDI missing.

And i think if can solve this issue, there are many more ahead ;)

Soooo, how can i get this thing rolling?

**Comment by cyberjunk** [comment]
Let me try to clarify some things...

1) You need to clone/checkout the <a href="https://github.com/cyberjunk/meridian59-dotnet">meridian59-dotnet</a> repository. If you plan to contribute, then clone this repository and checkout your clone.

2) The checkout will be huge, especially because there are 2 other repositories linked into subfolders (<a href="https://github.com/cyberjunk/meridian59-engine">Engine</a> and <a href="https://github.com/cyberjunk/meridian59-resources">Resources</a>, both are GIT repositories on their own and should be automatically checked out with the root repository)

3) Before you can build OgreClient, you need to build the Engine (this is only required for OgreClient). To do so, open /Engine/src/Engine.sln and build all 4 variants (x86/x64 in debug/release). This will take a long time and it will create ~10GB of static libraries in /Engine/lib - so be prepared for this. If you miss this step and try to build OgreClient, it will complain about missing *.lib files. You don't need to repeat this step each time you want to build OgreClient, only when the Engine changes (what doesn't happen very often).

4) You should be working with the Meridian59.sln file in the root of the repository to build any Meridian59 related projects. Don't open the project files directly. Please make sure you don't try to build the AnyCPU variant, this only works for the core-library and is supposed to be used with other platforms than Windows - so build x86 or x64!

5) I'm currently working with VS2013, so all project/solutions are still VS2013. Some time ago I made sure the Engine is compatible with VS2015, but I don't plan to migrate yet.

Hope that helps ?!

**Comment by m59solo** [comment]
Yes, this helps, thank you. I would never try it this way xD
I update abd close this issue if i get it running - but no time the next days.

**Comment by m59solo** [comment]
Can build it now. But if i start the exe there are all textures missing and if i debug in vc i get an error regarding recource not found. I think it cannot find client ressources (sound, textures etc.)
whats the trick here? :)

**Comment by cyberjunk** [comment]
>> But if i start the exe there are all textures missing and if i debug in vc i get an error regarding recource not found. I think it cannot find client ressources (sound, textures etc.)
whats the trick here? :)

BGF files are not included in the github repository. There is some copyright concerns, so the classic codebases don't include them either.

You have to copy all the grdXXXXX.bgf files from an updated client to the github /resources/bgftextures.
And all other .bgf files to /resources/bgfobjects.

**Comment by m59solo** [comment]
OK, thank you! Can build and test now.
