### ISSUE TITLE
Room Spell Icons

### ISSUE THREAD

**Issue by SaschaOFC** [cyberjunk/meridian59-dotnet#94]
The icons for a room spell (like killing fields) are really small.

Maybe add something like this i saw on another image:

<img width="190" alt="bildschirmfoto 2016-01-11 um 14 12 45" src="https://cloud.githubusercontent.com/assets/9608434/12234774/92bb90da-b86f-11e5-9854-ac84d6d787f6.png">

**Comment by cyberjunk** [comment]
Hehe, this is from World of Warcraft :-D
Two things:

1) I know you are not specifically asking for it, but so far I can't show the duration that's left. We would need to slightly modify the network protocl here, because this data is not available to the client (the text you get when clicking it is a different story).

2) I can very easily just increase the buff-icon sizes, but the resolution of the source images is a bit limited. Will see how much bigger I can make them...

**Comment by SaschaOFC** [comment]
@cyberjunk Sorry, i don't talk about the duration.

I would suggest to just increase the size and make a grey window behind it, just for an better view.

**Comment by skittles1** [comment]
Think this is technically fixed now, the icons look the same size as classic.
